import { faWifi, faSwimmingPool, faUtensils, faSpa, faCar, faTv, faSnowflake, faShuttleVan } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";


const roomsData = [
  // 🏨 Hotels
  {
    id: 1,
    name: "Skyline Premium Suite",
    type: "Hotel",
    category: "hotel",
    price: "₹18,000 / night",
    location: "Dubai, UAE",
    image: [
      "/hotelimg1.1.webp",
      "/hotelimg1.2.webp",
      "/hotelimg1.3.webp",
      "/hotelimg1.4.webp",
    ],
    rating: 4.9,
    reviews: 120,
    bedType: "King Bed",
    amenities: [
      { name: "Free WiFi", icon: faWifi },
      { name: "Infinity Pool", icon: faSwimmingPool },
      { name: "Spa Access", icon: faSpa },
      { name: "Airport Shuttle", icon: faShuttleVan },
    ],
    services: ["24/7 Room Service", "Complimentary Breakfast", "Daily Housekeeping"],
  },
  {
    id: 2,
    name: "Seaview Grand Palace",
    type: "Hotel",
    category: "hotel",
    price: "₹14,500 / night",
    location: "Goa, India",
    image: [
      "/hotelimg2.1.webp",
      "/hotelimg2.2.webp",
      "/hotelimg2.3.webp",
      "/hotelimg2.4.webp",
    ],
    rating: 4.8,
    reviews: 98,
    bedType: "Queen Bed",
    amenities: [
      { name: "Free WiFi", icon: faWifi },
      { name: "Sea View Balcony", icon: faTv },
      { name: "Outdoor Pool", icon: faSwimmingPool },
      { name: "Air Conditioning", icon: faSnowflake },
    ],
    services: ["Room Service", "Daily Cleaning", "Complimentary Drinks"],
  },
  {
    id: 3,
    name: "Mountain Escape Resort",
    type: "Hotel",
    category: "hotel",
    price: "₹12,800 / night",
    location: "Shimla, India",
    image: [
      "/hotelimg3.1.webp",
      "/hotelimg3.2.webp",
      "/hotelimg3.3.webp",
      "/hotelimg3.4.webp",
    ],
    rating: 4.7,
    reviews: 84,
    bedType: "Double Bed",
    amenities: [
      { name: "Free WiFi", icon: faWifi },
      { name: "Mountain View Deck", icon: faTv },
      { name: "Heated Pool", icon: faSwimmingPool },
      { name: "Spa & Sauna", icon: faSpa },
    ],
    services: ["Room Service", "Guided Trekking Tours", "Bonfire Nights"],
  },
  {
    id: 4,
    name: "City Lights Luxury Hotel",
    type: "Hotel",
    category: "hotel",
    price: "₹10,500 / night",
    location: "Bangalore, India",
    image: [
      "/hotelimg4.1.webp",
      "/hotelimg4.2.webp",
      "/hotelimg4.3.webp",
      "/hotelimg4.4.webp",
    ],
    rating: 4.6,
    reviews: 75,
    bedType: "Twin Beds",
    amenities: [
      { name: "Free WiFi", icon: faWifi },
      { name: "Rooftop Pool", icon: faSwimmingPool },
      { name: "Gym Access", icon: faCar },
      { name: "Flat Screen TV", icon: faTv },
    ],
    services: ["Express Check-in", "Business Lounge", "Laundry Service"],
  },

  // 🏡 Villas & Airbnb Stays
  {
    id: 5,
    name: "Luxury Beachfront Villa",
    type: "Villa",
    category: "villa",
    price: "₹25,000 / night",
    location: "Bali, Indonesia",
   image: [
      "/hotelimg5.1.avif",
      "/hotelimg5.2.avif",
      "/hotelimg5.3.avif",
      "/hotelimg5.4.avif",
    ],
    rating: 5.0,
    reviews: 143,
    bedType: "2 King Beds + Private Lounge",
    amenities: [
      { name: "Private Pool", icon: faSwimmingPool },
      { name: "Jacuzzi", icon: faSpa },
      { name: "Personal Chef", icon: faUtensils },
      { name: "Free WiFi", icon: faWifi },
    ],
    services: ["Butler Service", "Private Beach Access", "Daily Breakfast"],
  },
  {
    id: 6,
    name: "Rustic Wooden Cottage",
    type: "Airbnb",
    category: "villa",
    price: "₹7,500 / night",
    location: "Manali, India",
       image: [
      "/hotelimg6.1.avif",
      "/hotelimg6.2.avif",
      "/hotelimg6.3.avif",
      "/hotelimg6.4.avif",
    ],
    rating: 4.7,
    reviews: 54,
    bedType: "Double Bed",
    amenities: [
      { name: "Free WiFi", icon: faWifi },
      { name: "Mountain View Balcony", icon: faTv },
      { name: "Heater", icon: faSnowflake },
      { name: "Outdoor Fireplace", icon: faSpa },
    ],
    services: ["Homemade Breakfast", "Guided Hiking", "Bonfire Nights"],
  },
  {
    id: 7,
    name: "Infinity Pool Villa",
    type: "Villa",
    category: "villa",
    price: "₹32,000 / night",
    location: "Maldives",
       image: [
      "/hotelimg7.1.avif",
      "/hotelimg7.2.avif",
      "/hotelimg7.3.avif",
      "/hotelimg7.4.avif",
    ],
    rating: 5.0,
    reviews: 132,
    bedType: "King Bed + Ocean Deck",
    amenities: [
      { name: "Infinity Pool", icon: faSwimmingPool },
      { name: "Private Jacuzzi", icon: faSpa },
      { name: "Chef on Call", icon: faUtensils },
      { name: "Free WiFi", icon: faWifi },
    ],
    services: ["Floating Breakfast", "Private Snorkeling Tours", "Luxury Boat Rides"],
  },
  {
    id: 8,
    name: "Glasshouse Airbnb Retreat",
    type: "Airbnb",
    category: "villa",
    price: "₹9,000 / night",
    location: "Lonavala, India",
      image: [
      "/hotelimg8.1.avif",
      "/hotelimg8.2.avif",
      "/hotelimg8.3.avif",
      "/hotelimg8.4.avif",
    ],
    rating: 4.8,
    reviews: 67,
    bedType: "Queen Bed",
    amenities: [
      { name: "Glass Rooftop View", icon: faTv },
      { name: "Free WiFi", icon: faWifi },
      { name: "Outdoor Jacuzzi", icon: faSpa },
      { name: "Mini Bar", icon: faUtensils },
    ],
    services: ["BBQ Nights", "Daily Cleaning", "Personalized Concierge"],
  },
];

export default roomsData;
